fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.0.6
  symlinks:
    lmod: "#{source_dir}"
