fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.13.0
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
  symlinks:
    lmod: "#{source_dir}"
