---
.travis.yml:
  dist: xenial
  docker_defaults:
    dist: xenial
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
    - set: ubuntu-1404
      collection: puppet5
    - set: ubuntu-1404
      collection: puppet6
    - set: ubuntu-1604
      collection: puppet5
    - set: ubuntu-1604
      collection: puppet6
  user: treydock
  secure: "W0fQ2MZGvfB3+DBSPp8d0k+7o8gXkAHpNY5Ou4uBJZ0D8Hm5lLOzb6N28jtYDNXcEG2r7ovOAk2arDubptxqZUYcT92HwVwi8S5XlqxRA4MiLIr4Mu5v0XAgq8qlr5qaI0AurvjUQ0u6S+zF+FrqqorVm3TiNfAIxihPWDVGSRo="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
